### PR TITLE
Verify must be set to false to avoid SSL Exception

### PR DESCRIPTION
**Pull request by jumpkick**
- Fixes "SSL: CERTIFICATE_VERIFY_FAILED - certificate verify failed (_ssl.c:645)" that occurs if an https:// connection is made to the QNAP (since QNAP uses self-signed certs by default).

### CODE REVIEW

**Comment by colinodell** [comment]
I agree that bypassing the verification should be allowed, but I think that should be a configurable setting (in case someone has a legit cert and wants to guard against MITM attacks and the like).

**Comment by colinodell** [comment]
@jumpkick I've added a commit to make that option configurable.  Would you mind testing to confirm it works?

**Comment by colinodell** [comment]
I'm not using SSL certs, but this seems to work fine, so I'm going to merge this in.

**Comment by jumpkick** [comment]
I suspect the default ssl-cert is common to all QNAP devices, it's old, expired and weak.  Still, it's better than sending username and password in the clear over http.   If we could allow the default QNAP cert (which is the one most will use) and verify all other certs,  that might be an okay tradeoff of security vs convenience. 

I guess if I have to I can submit a patch up to home-assistant (I'd like to use your lib through their QNAP component) to allow the user to specify turning off verification in the config.

**Comment by jumpkick** [comment]
Patch submitted - https://github.com/home-assistant/home-assistant/pull/5927

**Comment by colinodell** [comment]
Sorry for not responding earlier, I actually submitted a patch up to HA a couple hours ago :) home-assistant/home-assistant#5919

**Pull request merged**
